[package]
name = "tauri-plugin-log"
version = "0.1.0"
authors = [ "Tauri Programme within The Commons Conservancy" ]
edition = "2018"

[dependencies]
tauri = "1.0.0-beta.8"
serde = "1.0"
serde_json = "1.0"
serde_repr = "0.1"
byte-unit = "4.0"
fern = "0.6"
log = "0.4"
chrono = "0.4"
